/**
 * This file deals with reading the csv file and converting the csv data
 * into JSON.
 */
"use strict";
/**
 * Listener to load event in XMLHttpRequest
 */
function xmlListener(){
  let csvData = xmlReq.responseText;
  let res = csvJSON(csvData);
  //console.log(res);
  localStorage.setItem('data', res);
}
/**
 * Listner to error event in XMLHttpRequest
 */
function transferError(){
  console.error("An error occurred while transferring the file.");
}
/**
 * Listener to prgress event in XMLHttpRequest
 */
function transferProgress(){
  console.log("Progressing...");
}
var xmlReq = new XMLHttpRequest();
xmlReq.addEventListener("load", xmlListener);
xmlReq.addEventListener("error", transferError);
xmlReq.addEventListener("progress", transferProgress);
xmlReq.open("GET", "https://ajayposhak.github.io/sachin.csv");
xmlReq.send();

/**
 * @param  {object} csv data generated by parsing the file.
 * @return {object} JSON object is returned after processing.
 */
function csvJSON(csv){
  var lines=csv.split("\n");
  var result = [];
  var headers=lines[0].split(",");
  for(var i=1;i<lines.length;i++){
	  var obj = {};
	  var currentline=lines[i].split(",");
	  for(var j=0;j<headers.length;j++){
		  obj[headers[j]] = currentline[j];
	  }
	  result.push(obj);
  }
  return JSON.stringify(result); //JSON
}
